coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 3%
        paths: "./src/"
    patch:
      default:
        # basic
        target: auto
        threshold: 3%
        paths: "./src/"
